# Generated by Django 5.1.4 on 2025-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='img',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
